/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.device.struts.action;

import java.io.BufferedReader;
import java.io.FileOutputStream;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.io.OutputStreamWriter;
import java.text.SimpleDateFormat;
import java.util.Calendar;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.bean.ComBean;
import com.util.Constant;

/** 
 * MyEclipse Struts
 * Creation date: 11-26-2013
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 */
public class AdminAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		try {
			request.setCharacterEncoding("gb2312");
		} catch (Exception ex) {
			// TODO Auto-generated catch block
			ex.printStackTrace();
		}	
		String strr="";
		try{
			ComBean cBean = new ComBean();
			String date=new SimpleDateFormat("yyyy-MM-dd HH:mm:ss").format(Calendar.getInstance().getTime());
			String date2=new SimpleDateFormat("yyyy-MM-dd").format(Calendar.getInstance().getTime());
			String method = request.getParameter("method");
			HttpSession session = request.getSession();
			if(method.equals("one")){//admin登录
				String username = request.getParameter("username");
				String password = request.getParameter("password"); 
				String str=cBean.getString("select id from admin where username='"+username+"' and  password='"+password+"'");
				if(str==null){
					request.setAttribute("message", "登录信息错误！");
					request.getRequestDispatcher("admin/login.jsp").forward(request, response); 
				}
				else{
					session.setAttribute("user", username);session.setAttribute("sf", "管理员");
					request.getRequestDispatcher("admin/index.jsp").forward(request, response); 
				}
			}
			else if(method.equals("uppwd")){//修改密码
				String username=(String)session.getAttribute("user"); 
				String oldpwd = request.getParameter("oldpwd"); 
				String newpwd = request.getParameter("newpwd"); 
				if(username.equals("admin")){
					String str=cBean.getString("select id from admin where username='"+username+"' and  password='"+oldpwd+"'");
					if(str==null){
						request.setAttribute("message", "原始密码信息错误！");
						request.getRequestDispatcher("admin/system/editpwd.jsp").forward(request, response); 
					}
					else{
						int flag=cBean.comUp("update admin set password='"+newpwd+"' where username='"+username+"'");
						if(flag == Constant.SUCCESS){ 
							request.setAttribute("message", "操作成功！");
							request.getRequestDispatcher("admin/system/editpwd.jsp").forward(request, response); 
						}
						else { 
							request.setAttribute("message", "操作失败！");
							request.getRequestDispatcher("admin/system/editpwd.jsp").forward(request, response); 
						}
					}
				}
				else{
					String str=cBean.getString("select id from teacher where username='"+username+"' and  password='"+oldpwd+"'");
					if(str==null){
						request.setAttribute("message", "原始密码信息错误！");
						request.getRequestDispatcher("admin/system/editpwd.jsp").forward(request, response); 
					}
					else{
						int flag=cBean.comUp("update teacher set password='"+newpwd+"' where username='"+username+"'");
						if(flag == Constant.SUCCESS){ 
							request.setAttribute("message", "操作成功！");
							request.getRequestDispatcher("admin/system/editpwd.jsp").forward(request, response); 
						}
						else { 
							request.setAttribute("message", "操作失败！");
							request.getRequestDispatcher("admin/system/editpwd.jsp").forward(request, response); 
						}
					}
				}
			}
			else if(method.equals("adminexit")){//退出登录
				session.removeAttribute("user");
				request.getRequestDispatcher("index.jsp").forward(request, response); 
			}
			else if(method.equals("addteacher")){//增加用户
				String username = request.getParameter("username"); 
				String password = request.getParameter("password"); 
				String realname = request.getParameter("realname"); 
				String sex = request.getParameter("sex"); 
				String age = request.getParameter("age"); 
				String tel = request.getParameter("tel"); 
				String address = request.getParameter("address");
				String str=cBean.getString("select id from teacher where username='"+username+"'");
				if(str==null){ 
					
						int flag=cBean.comUp("insert into teacher(username,password,realname,sex,age,tel,address) " +
							"values('"+username+"','"+password+"','"+realname+"','"+sex+"','"+age+"','"+tel+"','"+address+"' )");
						if(flag == Constant.SUCCESS){ 
							request.setAttribute("message", "操作成功！");
							request.getRequestDispatcher("admin/teacher/index.jsp").forward(request, response); 
						}
						else { 
							request.setAttribute("message", "操作失败！");
							request.getRequestDispatcher("admin/teacher/index.jsp").forward(request, response); 
						}
					 
					
				}
				else{
					request.setAttribute("message", "该用户名已存在！");
					request.getRequestDispatcher("admin/teacher/index.jsp").forward(request, response); 
				} 
			}
			else if(method.equals("upteacher")){//修改用户
				String id = request.getParameter("id");
				String username = request.getParameter("username"); 
				String password = request.getParameter("password"); 
				String realname = request.getParameter("realname"); 
				String sex = request.getParameter("sex"); 
				String age = request.getParameter("age"); 
				String tel = request.getParameter("tel"); 
				String address = request.getParameter("address");
				
				String str=cBean.getString("select id from teacher where username='"+username+"' and id!='"+id+"'");
				if(str==null){ 
					int flag=cBean.comUp("update teacher set username='"+username+"',password='"+password+"',realname='"+realname+"',sex='"+sex+"',age='"+age+"'," +
							"tel='"+tel+"',address='"+address+"' where id='"+id+"'");
					if(flag == Constant.SUCCESS){ 
						request.setAttribute("message", "操作成功！");
						request.getRequestDispatcher("admin/teacher/index.jsp").forward(request, response); 
					}
					else { 
						request.setAttribute("message", "操作失败！");
						request.getRequestDispatcher("admin/teacher/index.jsp").forward(request, response); 
					}
				}
				else{
					request.setAttribute("message", "该用户名已存在！");
					request.getRequestDispatcher("admin/teacher/index.jsp").forward(request, response); 
				} 
			}
			else if(method.equals("delteacher")){//删除用户
				String id = request.getParameter("id");  
				int flag=cBean.comUp("delete from teacher where id='"+id+"'");
				if(flag == Constant.SUCCESS){ 
					request.setAttribute("message", "操作成功！");
					request.getRequestDispatcher("admin/teacher/index.jsp").forward(request, response); 
				}
				else { 
					request.setAttribute("message", "操作失败！");
					request.getRequestDispatcher("admin/teacher/index.jsp").forward(request, response); 
				}
			}
			else if(method.equals("ifuse")){//停用/在用 用户
				String id = request.getParameter("id");  
				String sql="";
				String str=cBean.getString("select ifuse from teacher where id='"+id+"'");
				if(str.equals("在用")){
					sql="update teacher set ifuse='停用' where id='"+id+"'";
				}
				else{
					sql="update teacher set ifuse='在用' where id='"+id+"'";
				}
				int flag=cBean.comUp(sql);
				if(flag == Constant.SUCCESS){
					request.setAttribute("message", "操作成功！");
					request.getRequestDispatcher("admin/teacher/index.jsp").forward(request, response); 
				}
				else{
					request.setAttribute("message", "操作失败！");
					request.getRequestDispatcher("admin/teacher/index.jsp").forward(request, response); 
				}
			}
			else if(method.equals("bf")){// 
				try {       
		            Runtime rt = Runtime.getRuntime();       
		      
		            // 调用 mysql 的 cmd 
		Process child = rt.exec("D:/Program Files/MySQL/MySQL Server 5.5/bin/mysqldump -uroot -p123  czc");// 设置导出编码为utf8。这里必须是utf8       
		                  
		            // 把进程执行中的控制台输出信息写入.sql文件，即生成了备份文件。注：如果不对控制台信息进行读出，则会导致进程堵塞无法运行       
		            InputStream in = child.getInputStream();// 控制台的输出信息作为输入流       
		                              
		            InputStreamReader xx = new InputStreamReader(in, "utf8");// 设置输出流编码为utf8。这里必须是utf8，否则从流中读入的是乱 

		            String inStr;       
		            StringBuffer sb = new StringBuffer("");       
		            String outStr;       
		            // 组合控制台输出信息字符串       
		            BufferedReader br = new BufferedReader(xx);       
		            while ((inStr = br.readLine()) != null) {       
		                sb.append(inStr + "\r\n");       
		            }       
		            outStr = sb.toString();       
		                  
		            // 要用来做导入用的sql目标文件：       
		            FileOutputStream fout = new FileOutputStream("d:/db.sql");       
		            OutputStreamWriter writer = new OutputStreamWriter(fout, "utf8");       
		            writer.write(outStr);       
		            // 注：这里如果用缓冲方式写入文件的话，会导致中文乱码，用flush()方法则可以避免       
		            writer.flush();       
		      
		            // 别忘记关闭输入输出流       
		            in.close 
		();       
		             
		xx.close();       
		            br.close();       
		            writer.close();       
		            fout.close();       
		      
		            System.out.println("");
		            request.setAttribute("message", "操作成功！");
					request.getRequestDispatcher("admin/bf/index.jsp").forward(request, response);       
		      
		        } catch (Exception e) {       
		            e.printStackTrace();       
		        }       
			}
			
			
			
			
			
			else if(method.equals("addjsy")){//增加驾驶员
				String username = request.getParameter("username"); 
				String password = request.getParameter("password"); 
				String realname = request.getParameter("realname"); 
				String sex = request.getParameter("sex"); 
				String age = request.getParameter("age"); 
				String tel = request.getParameter("tel"); 
				String address = request.getParameter("address");
				String str=cBean.getString("select id from jsy where username='"+username+"'");
				if(str==null){ 
					
						int flag=cBean.comUp("insert into jsy(username,password,realname,sex,age,tel,address) " +
							"values('"+username+"','"+password+"','"+realname+"','"+sex+"','"+age+"','"+tel+"','"+address+"' )");
						if(flag == Constant.SUCCESS){ 
							request.setAttribute("message", "操作成功！");
							request.getRequestDispatcher("admin/jsy/index.jsp").forward(request, response); 
						}
						else { 
							request.setAttribute("message", "操作失败！");
							request.getRequestDispatcher("admin/jsy/index.jsp").forward(request, response); 
						}
					 
					
				}
				else{
					request.setAttribute("message", "该驾驶员编号已存在！");
					request.getRequestDispatcher("admin/jsy/index.jsp").forward(request, response); 
				} 
			}
			else if(method.equals("upjsy")){//修改驾驶员
				String id = request.getParameter("id");
				String username = request.getParameter("username"); 
				String password = request.getParameter("password"); 
				String realname = request.getParameter("realname"); 
				String sex = request.getParameter("sex"); 
				String age = request.getParameter("age"); 
				String tel = request.getParameter("tel"); 
				String address = request.getParameter("address");
				
				String str=cBean.getString("select id from jsy where username='"+username+"' and id!='"+id+"'");
				if(str==null){ 
					int flag=cBean.comUp("update jsy set username='"+username+"',password='"+password+"',realname='"+realname+"',sex='"+sex+"',age='"+age+"'," +
							"tel='"+tel+"',address='"+address+"' where id='"+id+"'");
					if(flag == Constant.SUCCESS){ 
						request.setAttribute("message", "操作成功！");
						request.getRequestDispatcher("admin/jsy/index.jsp").forward(request, response); 
					}
					else { 
						request.setAttribute("message", "操作失败！");
						request.getRequestDispatcher("admin/jsy/index.jsp").forward(request, response); 
					}
				}
				else{
					request.setAttribute("message", "该驾驶员编号已存在！");
					request.getRequestDispatcher("admin/jsy/index.jsp").forward(request, response); 
				} 
			}
			else if(method.equals("deljsy")){//删除驾驶员
				String id = request.getParameter("id");  
				int flag=cBean.comUp("delete from jsy where id='"+id+"'");
				if(flag == Constant.SUCCESS){ 
					request.setAttribute("message", "操作成功！");
					request.getRequestDispatcher("admin/jsy/index.jsp").forward(request, response); 
				}
				else { 
					request.setAttribute("message", "操作失败！");
					request.getRequestDispatcher("admin/jsy/index.jsp").forward(request, response); 
				}
			}
			else{//无参数传入转到错误页面
				request.getRequestDispatcher("error.jsp").forward(request, response);
			}
		}
		catch(Exception e){
			e.printStackTrace();
			return mapping.findForward("error.jsp"); 
		}
		return mapping.findForward(strr);
	} 
}