/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.device.struts.action;

import java.io.BufferedReader;
import java.io.FileOutputStream;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.io.OutputStreamWriter;
import java.math.BigDecimal;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.bean.ComBean;
import com.util.Constant;

/** 
 * MyEclipse Struts
 * Creation date: 11-26-2013
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 */
public class ComAction extends Action {
	/*
	 * Generated Methods
	 */
	
	public static void main(String[] args) {
		String username = "qq";
		String jsyname = "qq";
		String hm = "qq";
		String departure = "qq";
		String arrival = "qq";
		String distance = "12";
		String createtime = "2017-04-07 00:00:00";
		String amount = "12";
		String status = "是";
		StringBuffer sb = new StringBuffer("insert into taxi.order(username, jsyname, hm, departure, arrival, distance, createtime, amount, status, comment) values (");
		sb.append("'" + username + "','" + jsyname + "','" + hm + "','" + departure + "','" + arrival + "','" + distance + "','" + createtime + "','" + amount + "','" + status + "','" + "'")
		.append(")");
		System.out.println(sb.toString());
	}
	
	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		try {
			request.setCharacterEncoding("gb2312");
		} catch (Exception ex) {
			// TODO Auto-generated catch block
			ex.printStackTrace();
		}	
		String strr="";
		try{
			ComBean cBean = new ComBean();
			String date=new SimpleDateFormat("yyyy-MM-dd HH:mm:ss").format(Calendar.getInstance().getTime());
			String date2=new SimpleDateFormat("yyyy-MM-dd").format(Calendar.getInstance().getTime());
			String method = request.getParameter("method"); 

			if(method.equals("addclasses")){//			增加车辆信息管理  
				String hm=request.getParameter("hm");
				String pp=request.getParameter("pp");
				String lx=request.getParameter("lx");
				String cj=request.getParameter("cj");
				String bz=request.getParameter("bz");
				 
					int flag=cBean.comUp("insert into classes(hm,pp,lx,cj,bz) values('"+hm+"','"+pp+"','"+lx+"','"+cj+"','"+bz+"')");
					if(flag==Constant.SUCCESS){
						request.setAttribute("message", "操作成功！");
						request.getRequestDispatcher("admin/classes/index.jsp").forward(request, response);
					}
					else{
						request.setAttribute("message", "系统维护中！");
						request.getRequestDispatcher("admin/classes/index.jsp").forward(request, response);
					}
				 
			}
			// 用户预约车辆，即下单
			else if(method.equals("addorder")) {
				String username = request.getParameter("username"); // 用户名
				String hm = request.getParameter("hm"); // 车牌号码
				String jsyname = request.getParameter("jsyname"); // 驾驶员名称
				String departure = request.getParameter("departure"); // 出发地
				String arrival = request.getParameter("arrival"); // 到达地
				String distance = request.getParameter("distance"); // 距离
				
				BigDecimal price = new BigDecimal(3); // 约定单价为3块钱每公里，这个价格就是参考，可以随时修改
				BigDecimal amount = price.multiply(new BigDecimal(distance)); // 根据用户填写的里程数来计算金额
				
				String createtime = date;// 当前日期即创单时间，这里约定就是用车时间
				
				String status = "已预约"; // 用户下单，新单状态为已预约
				
				StringBuffer sb = new StringBuffer("insert into taxi.order(username, jsyname, hm, departure, arrival, distance, createtime, amount, status, comment) values (");
				sb.append("'" + username + "','" + jsyname + "','" + hm + "','" + departure + "','" + arrival + "','" + distance + "','" + createtime + "','" + amount + "','" + status + "','" + "'")
				.append(")");
				int flag=cBean.comUp(sb.toString());
				if(flag==Constant.SUCCESS){
					request.setAttribute("message", "操作成功！");
					request.getRequestDispatcher("admin/order/index.jsp").forward(request, response);
				}
				else{
					request.setAttribute("message", "系统维护中！");
					request.getRequestDispatcher("admin/order/index.jsp").forward(request, response);
				}
			}
			// 管理员操作订单：接单（修改状态为已接单），结单（修改状态为已结单）
			else if(method.equals("uporder")) {
				String id = request.getParameter("id");
				String type = request.getParameter("type");
				StringBuffer sql = new StringBuffer("update taxi.order set status = '");
				sql.append(type.equals("accept") ? "已接单" : "已结单"); // 如果type是accept的话，修改状态为已接单，如果是close的话修改为已结单
				sql.append("' where id = " + id);
				int flag = cBean.comUp(sql.toString());
				if(flag == Constant.SUCCESS){
					request.setAttribute("message", "操作成功！");
					request.getRequestDispatcher("admin/order/index.jsp").forward(request, response);
				}
				else{
					request.setAttribute("message", "操作失败！");
					request.getRequestDispatcher("admin/order/index.jsp").forward(request, response);
				} 
			}
			// 用户为已结单的订单添加评论
			else if(method.equals("commentorder")) {
				String id = request.getParameter("id");
				String comment = request.getParameter("comment");
				int flag = cBean.comUp("update taxi.order set comment = '" + comment + "' where id = '" + id + "'");
				if(flag == Constant.SUCCESS){
					request.setAttribute("message", "操作成功！");
					request.getRequestDispatcher("admin/order/index.jsp").forward(request, response);
				}
				else{
					request.setAttribute("message", "操作失败！");
					request.getRequestDispatcher("admin/order/index.jsp").forward(request, response);
				}
			}
			// 添加位置信息
			else if(method.equals("addrecord")) {
				String hm=request.getParameter("hm");
				String pp=request.getParameter("pp");
				String lx=request.getParameter("lx");
				
				int flag=cBean.comUp("insert into record(hm,location,currenttime) values('"+hm+"','"+pp+"','"+lx+"')");
				if(flag==Constant.SUCCESS){
					request.setAttribute("message", "操作成功！");
					request.getRequestDispatcher("admin/record/index.jsp").forward(request, response);
				}
				else{
					request.setAttribute("message", "系统维护中！");
					request.getRequestDispatcher("admin/record/index.jsp").forward(request, response);
				}
			}
			// 修改位置信息
			else if(method.equals("uprecord")) {
				String id=request.getParameter("id");
				String hm=request.getParameter("hm");
				String pp=request.getParameter("pp");
				String lx=request.getParameter("lx");
				int flag = cBean.comUp("update record set hm='"+hm+"',location='"+pp+"',currenttime='"+lx+"' where id='"+id+"'");
				if(flag == Constant.SUCCESS){
					request.setAttribute("message", "操作成功！");
					request.getRequestDispatcher("admin/record/index.jsp").forward(request, response);
				}
				else{
					request.setAttribute("message", "操作失败！");
					request.getRequestDispatcher("admin/record/index.jsp").forward(request, response);
				}
			}
			// 删除位置信息
			else if(method.equals("delrecord")) {
				String id=request.getParameter("id"); 
				int flag=cBean.comUp("delete from record where id='"+id+"'");
				if(flag==Constant.SUCCESS){
					request.setAttribute("message", "操作成功！");
					request.getRequestDispatcher("admin/record/index.jsp").forward(request, response);
				}
				else{
					request.setAttribute("message", "系统维护中！");
					request.getRequestDispatcher("admin/record/index.jsp").forward(request, response);
				}
			}
			else if(method.equals("upclasses")){ //修改车辆
				String id=request.getParameter("id");
				String type = request.getParameter("type");
				if(type.equals("disqualify")) {
					// 取消网约车资格
					int flag = cBean.comUp("update classes set isactive = '否' where id = '" + id + "'");
					if(flag == Constant.SUCCESS){
						request.setAttribute("message", "操作成功！");
						request.getRequestDispatcher("admin/classes/index.jsp").forward(request, response);
					}
					else{
						request.setAttribute("message", "操作失败！");
						request.getRequestDispatcher("admin/classes/index.jsp").forward(request, response);
					}
				} else if(type.equals("qualify")) {
					int flag = cBean.comUp("update classes set isactive = '是' where id = '" + id + "'");
					if(flag == Constant.SUCCESS){
						request.setAttribute("message", "操作成功！");
						request.getRequestDispatcher("admin/classes/index.jsp").forward(request, response);
					}
					else{
						request.setAttribute("message", "操作失败！");
						request.getRequestDispatcher("admin/classes/index.jsp").forward(request, response);
					}
				} else {
					String hm=request.getParameter("hm");
					String pp=request.getParameter("pp");
					String lx=request.getParameter("lx");
					String cj=request.getParameter("cj");
					String bz=request.getParameter("bz"); 
					int flag = cBean.comUp("update classes set hm='"+hm+"',pp='"+pp+"',lx='"+lx+"',cj='"+cj+"',bz='"+bz+"' where id='"+id+"'");
					if(flag == Constant.SUCCESS){
						request.setAttribute("message", "操作成功！");
						request.getRequestDispatcher("admin/classes/index.jsp").forward(request, response);
					}
					else{
						request.setAttribute("message", "操作失败！");
						request.getRequestDispatcher("admin/classes/index.jsp").forward(request, response);
					}
				}
			}
			//删除车辆信息管理
			else if(method.equals("delclasses")){
				String id=request.getParameter("id"); 
				int flag=cBean.comUp("delete from classes where id='"+id+"'");
				if(flag==Constant.SUCCESS){
					 
					request.setAttribute("message", "操作成功！");
					request.getRequestDispatcher("admin/classes/index.jsp").forward(request, response);
				}
				else{
					request.setAttribute("message", "系统维护中！");
					request.getRequestDispatcher("admin/classes/index.jsp").forward(request, response);
				}
			}
			else if(method.equals("upclasses")){ 
				String id=request.getParameter("id");
				String title=request.getParameter("title");
				String content=request.getParameter("infoContent");
					int flag = cBean.comUp("update classes set title='"+title+"',content='"+content+"'  where id='"+id+"'");
					if(flag == Constant.SUCCESS){
						request.setAttribute("message", "操作成功！");
						request.getRequestDispatcher("admin/classes/index.jsp").forward(request, response);
					}
					else{
						request.setAttribute("message", "操作失败！");
						request.getRequestDispatcher("admin/classes/index.jsp").forward(request, response);
					}
				 
			}
			//增加车信息 
			else if(method.equals("addgyc")){  
				//String id="";String cid = "";String jsy=""; String db=""; 
				String cid = request.getParameter("cid");
				String swjsy = request.getParameter("swjsy"); 
				String xwjsy = request.getParameter("xwjsy"); 
				
				String cphm=cBean.getString("select hm from classes where id='"+cid+"'");
				
				if(swjsy.equals(xwjsy)){
					request.setAttribute("message", "上下午班司机不能为同一个！");
					request.getRequestDispatcher("admin/gyc/index.jsp").forward(request, response);
				}
				else{
					String str=cBean.getString("select id from gyc where cid='"+cid+"'  ");
					if(str==null){
						String str2=cBean.getString("select id from gyc where swjsy='"+swjsy+"' or xwjsy='"+xwjsy+"'");
						if(str2==null){
							int flag = cBean.comUp("insert into gyc(cid,swjsy,xwjsy,sj ,cphm)  values('"+cid+"','"+swjsy+"','"+xwjsy+"','"+date2+"','"+cphm+"' )");
							if(flag == Constant.SUCCESS){
								request.setAttribute("message", "操作成功！");
								request.getRequestDispatcher("admin/gyc/index.jsp").forward(request, response);
							}
							else{
								request.setAttribute("message", "操作失败！");
								request.getRequestDispatcher("admin/gyc/index.jsp").forward(request, response);
							}
						}
						else{
							request.setAttribute("message", "驾驶员排班冲突！");
							request.getRequestDispatcher("admin/gyc/index.jsp").forward(request, response);
						}
						
					}
					else{
						request.setAttribute("message", "该车已经排班！");
						request.getRequestDispatcher("admin/gyc/index.jsp").forward(request, response);
					}
				}
				
				
			} 
			//修改车信息
			else if(method.equals("upgyc")){ 
				String id=request.getParameter("id");
				String cid = request.getParameter("cid");
				String swjsy = request.getParameter("swjsy"); 
				String xwjsy = request.getParameter("xwjsy"); 
				
				if(swjsy.equals(xwjsy)){
					request.setAttribute("message", "上下午班司机不能为同一个！");
					request.getRequestDispatcher("admin/gyc/index.jsp").forward(request, response);
				}
				else{
					String str=cBean.getString("select xwjsy from gyc where cid='"+cid+"' and id!='"+id+"' ");
					if(str==null){
						String str2=cBean.getString("select xwjsy from gyc where swjsy='"+swjsy+"' or xwjsy='"+xwjsy+"' and id!='"+id+"' ");
						if(str2==null){
							int flag = cBean.comUp("insert into gyc(cid,swjsy,xwjsy )  values('"+cid+"','"+swjsy+"','"+xwjsy+"' )");
							if(flag == Constant.SUCCESS){
								request.setAttribute("message", "操作成功！");
								request.getRequestDispatcher("admin/gyc/index.jsp").forward(request, response);
							}
							else{
								request.setAttribute("message", "操作失败！");
								request.getRequestDispatcher("admin/gyc/index.jsp").forward(request, response);
							}
						}
						else{
							request.setAttribute("message", "驾驶员排班冲突！");
							request.getRequestDispatcher("admin/gyc/index.jsp").forward(request, response);
						}
						
					}
					else{
						request.setAttribute("message", "该车已经排班！");
						request.getRequestDispatcher("admin/gyc/index.jsp").forward(request, response);
					}
				}
			}
			//删除车信息
			else if(method.equals("delgyc")){
				String id = request.getParameter("id");
				int flag = cBean.comUp("delete from gyc where id='"+id+"'");
				if(flag == Constant.SUCCESS){
					request.setAttribute("message", "操作成功！");
					request.getRequestDispatcher("admin/gyc/index.jsp").forward(request, response);
				}
				else{
					request.setAttribute("message", "系统维护中，请稍后再试！");
					request.getRequestDispatcher("admin/gyc/index.jsp").forward(request, response);
				}
			}
			
			
			
			
			
			
			
			 
//			信息
			else if(method.equals("addtb")){
				//String id="";String hm = "";String pp=""; String lx=""; String cj=""; String bz=""; 
				String hm=request.getParameter("hm");
				String pp=request.getParameter("pp");
				String lx=request.getParameter("lx");
				String cj=request.getParameter("cj");
				String bz=request.getParameter("bz");
				 
					int flag=cBean.comUp("insert into tb(hm,pp,lx,cj,bz) values('"+hm+"','"+pp+"','"+lx+"','"+cj+"','"+bz+"')");
					if(flag==Constant.SUCCESS){
						request.setAttribute("message", "操作成功！");
						request.getRequestDispatcher("admin/tb/index.jsp").forward(request, response);
					}
					else{
						request.setAttribute("message", "系统维护中！");
						request.getRequestDispatcher("admin/tb/index.jsp").forward(request, response);
					}
				 
			}
			else if(method.equals("uptb")){ 
				String id=request.getParameter("id");
				String hm=request.getParameter("hm");
				String pp=request.getParameter("pp");
				String lx=request.getParameter("lx");
				String cj=request.getParameter("cj");
				String bz=request.getParameter("bz"); 
					int flag = cBean.comUp("update tb set hm='"+hm+"',pp='"+pp+"',lx='"+lx+"',cj='"+cj+"',bz='"+bz+"' where id='"+id+"'");
					if(flag == Constant.SUCCESS){
						request.setAttribute("message", "操作成功！");
						request.getRequestDispatcher("admin/tb/index.jsp").forward(request, response);
					}
					else{
						request.setAttribute("message", "操作失败！");
						request.getRequestDispatcher("admin/tb/index.jsp").forward(request, response);
					}
				 
			}
			//删除信息
			else if(method.equals("deltb")){
				String id=request.getParameter("id"); 
				int flag=cBean.comUp("delete from tb where id='"+id+"'");
				if(flag==Constant.SUCCESS){
					 
					request.setAttribute("message", "操作成功！");
					request.getRequestDispatcher("admin/tb/index.jsp").forward(request, response);
				}
				else{
					request.setAttribute("message", "系统维护中！");
					request.getRequestDispatcher("admin/tb/index.jsp").forward(request, response);
				}
			}
			else if(method.equals("uptb")){ 
				String id=request.getParameter("id");
				String title=request.getParameter("title");
				String content=request.getParameter("infoContent");
					int flag = cBean.comUp("update tb set title='"+title+"',content='"+content+"'  where id='"+id+"'");
					if(flag == Constant.SUCCESS){
						request.setAttribute("message", "操作成功！");
						request.getRequestDispatcher("admin/tb/index.jsp").forward(request, response);
					}
					else{
						request.setAttribute("message", "操作失败！");
						request.getRequestDispatcher("admin/tb/index.jsp").forward(request, response);
					}
				 
			}
			
			
			
			
			
			
			
			
			
//			信息
			else if(method.equals("addjf")){
				//String id="";String hm = "";String pp=""; String lx=""; String cj=""; String bz=""; 
				String hm=request.getParameter("hm");
				String pp=request.getParameter("pp");
				String lx=request.getParameter("lx");
				String cj=request.getParameter("cj");
				String bz=request.getParameter("bz");
				 
					int flag=cBean.comUp("insert into jf(hm,pp,lx,cj,bz) values('"+hm+"','"+pp+"','"+lx+"','"+cj+"','"+bz+"')");
					if(flag==Constant.SUCCESS){
						request.setAttribute("message", "操作成功！");
						request.getRequestDispatcher("admin/jf/index.jsp").forward(request, response);
					}
					else{
						request.setAttribute("message", "系统维护中！");
						request.getRequestDispatcher("admin/jf/index.jsp").forward(request, response);
					}
				 
			}
			else if(method.equals("upjf")){ 
				String id=request.getParameter("id");
				String hm=request.getParameter("hm");
				String pp=request.getParameter("pp");
				String lx=request.getParameter("lx");
				String cj=request.getParameter("cj");
				String bz=request.getParameter("bz"); 
					int flag = cBean.comUp("update jf set hm='"+hm+"',pp='"+pp+"',lx='"+lx+"',cj='"+cj+"',bz='"+bz+"' where id='"+id+"'");
					if(flag == Constant.SUCCESS){
						request.setAttribute("message", "操作成功！");
						request.getRequestDispatcher("admin/jf/index.jsp").forward(request, response);
					}
					else{
						request.setAttribute("message", "操作失败！");
						request.getRequestDispatcher("admin/jf/index.jsp").forward(request, response);
					}
				 
			}
			//删除信息
			else if(method.equals("deljf")){
				String id=request.getParameter("id"); 
				int flag=cBean.comUp("delete from jf where id='"+id+"'");
				if(flag==Constant.SUCCESS){
					 
					request.setAttribute("message", "操作成功！");
					request.getRequestDispatcher("admin/jf/index.jsp").forward(request, response);
				}
				else{
					request.setAttribute("message", "系统维护中！");
					request.getRequestDispatcher("admin/jf/index.jsp").forward(request, response);
				}
			}
			else if(method.equals("upjf")){ 
				String id=request.getParameter("id");
				String title=request.getParameter("title");
				String content=request.getParameter("infoContent");
					int flag = cBean.comUp("update jf set title='"+title+"',content='"+content+"'  where id='"+id+"'");
					if(flag == Constant.SUCCESS){
						request.setAttribute("message", "操作成功！");
						request.getRequestDispatcher("admin/jf/index.jsp").forward(request, response);
					}
					else{
						request.setAttribute("message", "操作失败！");
						request.getRequestDispatcher("admin/jf/index.jsp").forward(request, response);
					}
				 
			}
			
			
//			信息
			else if(method.equals("addns")){
				//String id="";String hm = "";String pp=""; String lx=""; String cj=""; String bz=""; 
				String hm=request.getParameter("hm");
				String pp=request.getParameter("pp");
				String lx=request.getParameter("lx");
				String cj=request.getParameter("cj");
				String bz=request.getParameter("bz");
				 
					int flag=cBean.comUp("insert into ns(hm,pp,lx,cj,bz) values('"+hm+"','"+pp+"','"+lx+"','"+cj+"','"+bz+"')");
					if(flag==Constant.SUCCESS){
						request.setAttribute("message", "操作成功！");
						request.getRequestDispatcher("admin/ns/index.jsp").forward(request, response);
					}
					else{
						request.setAttribute("message", "系统维护中！");
						request.getRequestDispatcher("admin/ns/index.jsp").forward(request, response);
					}
				 
			}
			else if(method.equals("upns")){ 
				String id=request.getParameter("id");
				String hm=request.getParameter("hm");
				String pp=request.getParameter("pp");
				String lx=request.getParameter("lx");
				String cj=request.getParameter("cj");
				String bz=request.getParameter("bz"); 
					int flag = cBean.comUp("update ns set hm='"+hm+"',pp='"+pp+"',lx='"+lx+"',cj='"+cj+"',bz='"+bz+"' where id='"+id+"'");
					if(flag == Constant.SUCCESS){
						request.setAttribute("message", "操作成功！");
						request.getRequestDispatcher("admin/ns/index.jsp").forward(request, response);
					}
					else{
						request.setAttribute("message", "操作失败！");
						request.getRequestDispatcher("admin/ns/index.jsp").forward(request, response);
					}
				 
			}
			//删除信息
			else if(method.equals("delns")){
				String id=request.getParameter("id"); 
				int flag=cBean.comUp("delete from ns where id='"+id+"'");
				if(flag==Constant.SUCCESS){
					 
					request.setAttribute("message", "操作成功！");
					request.getRequestDispatcher("admin/ns/index.jsp").forward(request, response);
				}
				else{
					request.setAttribute("message", "系统维护中！");
					request.getRequestDispatcher("admin/ns/index.jsp").forward(request, response);
				}
			}
			else if(method.equals("upns")){ 
				String id=request.getParameter("id");
				String title=request.getParameter("title");
				String content=request.getParameter("infoContent");
					int flag = cBean.comUp("update ns set title='"+title+"',content='"+content+"'  where id='"+id+"'");
					if(flag == Constant.SUCCESS){
						request.setAttribute("message", "操作成功！");
						request.getRequestDispatcher("admin/ns/index.jsp").forward(request, response);
					}
					else{
						request.setAttribute("message", "操作失败！");
						request.getRequestDispatcher("admin/ns/index.jsp").forward(request, response);
					}
				 
			}
			
			////////////////信息
//			信息
			else if(method.equals("addsg")){
				//String id="";String hm = "";String pp=""; String lx=""; String cj=""; String bz=""; 
				String hm=request.getParameter("hm");
				String pp=request.getParameter("pp");
				String lx=request.getParameter("lx");
				String cj=request.getParameter("cj");
				String bz=request.getParameter("bz");
				 
					int flag=cBean.comUp("insert into sg(hm,pp,lx,cj,bz) values('"+hm+"','"+pp+"','"+lx+"','"+cj+"','"+bz+"')");
					if(flag==Constant.SUCCESS){
						request.setAttribute("message", "操作成功！");
						request.getRequestDispatcher("admin/sg/index.jsp").forward(request, response);
					}
					else{
						request.setAttribute("message", "系统维护中！");
						request.getRequestDispatcher("admin/sg/index.jsp").forward(request, response);
					}
				 
			}
			else if(method.equals("upsg")){ 
				String id=request.getParameter("id");
				String hm=request.getParameter("hm");
				String pp=request.getParameter("pp");
				String lx=request.getParameter("lx");
				String cj=request.getParameter("cj");
				String bz=request.getParameter("bz"); 
					int flag = cBean.comUp("update sg set hm='"+hm+"',pp='"+pp+"',lx='"+lx+"',cj='"+cj+"',bz='"+bz+"' where id='"+id+"'");
					if(flag == Constant.SUCCESS){
						request.setAttribute("message", "操作成功！");
						request.getRequestDispatcher("admin/sg/index.jsp").forward(request, response);
					}
					else{
						request.setAttribute("message", "操作失败！");
						request.getRequestDispatcher("admin/sg/index.jsp").forward(request, response);
					}
				 
			}
			//删除信息
			else if(method.equals("delsg")){
				String id=request.getParameter("id"); 
				int flag=cBean.comUp("delete from sg where id='"+id+"'");
				if(flag==Constant.SUCCESS){
					 
					request.setAttribute("message", "操作成功！");
					request.getRequestDispatcher("admin/sg/index.jsp").forward(request, response);
				}
				else{
					request.setAttribute("message", "系统维护中！");
					request.getRequestDispatcher("admin/sg/index.jsp").forward(request, response);
				}
			} 
			
			
////////////////信息
//			信息
			else if(method.equals("addwz")){
				//String id="";String hm = "";String pp=""; String lx=""; String cj=""; String bz=""; 
				String hm=request.getParameter("hm");
				String pp=request.getParameter("pp");
				String lx=request.getParameter("lx");
				String cj=request.getParameter("cj");
				String bz=request.getParameter("bz");
				 
					int flag=cBean.comUp("insert into wz(hm,pp,lx,cj,bz) values('"+hm+"','"+pp+"','"+lx+"','"+cj+"','"+bz+"')");
					if(flag==Constant.SUCCESS){
						request.setAttribute("message", "操作成功！");
						request.getRequestDispatcher("admin/wz/index.jsp").forward(request, response);
					}
					else{
						request.setAttribute("message", "系统维护中！");
						request.getRequestDispatcher("admin/wz/index.jsp").forward(request, response);
					}
				 
			}
			else if(method.equals("upwz")){ 
				String id=request.getParameter("id");
				String hm=request.getParameter("hm");
				String pp=request.getParameter("pp");
				String lx=request.getParameter("lx");
				String cj=request.getParameter("cj");
				String bz=request.getParameter("bz"); 
					int flag = cBean.comUp("update wz set hm='"+hm+"',pp='"+pp+"',lx='"+lx+"',cj='"+cj+"',bz='"+bz+"' where id='"+id+"'");
					if(flag == Constant.SUCCESS){
						request.setAttribute("message", "操作成功！");
						request.getRequestDispatcher("admin/wz/index.jsp").forward(request, response);
					}
					else{
						request.setAttribute("message", "操作失败！");
						request.getRequestDispatcher("admin/wz/index.jsp").forward(request, response);
					}
				 
			}
			//删除信息
			else if(method.equals("delwz")){
				String id=request.getParameter("id"); 
				int flag=cBean.comUp("delete from wz where id='"+id+"'");
				if(flag==Constant.SUCCESS){
					 
					request.setAttribute("message", "操作成功！");
					request.getRequestDispatcher("admin/wz/index.jsp").forward(request, response);
				}
				else{
					request.setAttribute("message", "系统维护中！");
					request.getRequestDispatcher("admin/wz/index.jsp").forward(request, response);
				}
			} 
			
			
////////////信息
//			信息
			else if(method.equals("addzc")){
				//String id="";String hm = "";String pp=""; String lx=""; String cj=""; String bz=""; 
				String hm=request.getParameter("hm");
				String pp=request.getParameter("pp");
				String lx=request.getParameter("lx");
				String cj=request.getParameter("cj");
				String bz=request.getParameter("bz");
				 
					int flag=cBean.comUp("insert into zc(hm,pp,lx,cj,bz) values('"+hm+"','"+pp+"','"+lx+"','"+cj+"','"+bz+"')");
					if(flag==Constant.SUCCESS){
						request.setAttribute("message", "操作成功！");
						request.getRequestDispatcher("admin/zc/index.jsp").forward(request, response);
					}
					else{
						request.setAttribute("message", "系统维护中！");
						request.getRequestDispatcher("admin/zc/index.jsp").forward(request, response);
					}
				 
			}
			else if(method.equals("upzc")){ 
				String id=request.getParameter("id");
				String hm=request.getParameter("hm");
				String pp=request.getParameter("pp");
				String lx=request.getParameter("lx");
				String cj=request.getParameter("cj");
				String bz=request.getParameter("bz"); 
					int flag = cBean.comUp("update zc set hm='"+hm+"',pp='"+pp+"',lx='"+lx+"',cj='"+cj+"',bz='"+bz+"' where id='"+id+"'");
					if(flag == Constant.SUCCESS){
						request.setAttribute("message", "操作成功！");
						request.getRequestDispatcher("admin/zc/index.jsp").forward(request, response);
					}
					else{
						request.setAttribute("message", "操作失败！");
						request.getRequestDispatcher("admin/zc/index.jsp").forward(request, response);
					}
				 
			}
			//删除信息
			else if(method.equals("delzc")){
				String id=request.getParameter("id"); 
				int flag=cBean.comUp("delete from zc where id='"+id+"'");
				if(flag==Constant.SUCCESS){
					 
					request.setAttribute("message", "操作成功！");
					request.getRequestDispatcher("admin/zc/index.jsp").forward(request, response);
				}
				else{
					request.setAttribute("message", "系统维护中！");
					request.getRequestDispatcher("admin/zc/index.jsp").forward(request, response);
				}
			} 
			
			
			
////		信息
//			信息
			else if(method.equals("addts")){
				//String id="";String hm = "";String pp=""; String lx=""; String cj=""; String bz=""; 
				String hm=request.getParameter("hm");
				String pp=request.getParameter("pp");
				String lx=request.getParameter("lx");
				String cj=request.getParameter("cj");
				String bz=request.getParameter("bz");
				 
					int flag=cBean.comUp("insert into ts(hm,pp,lx,cj,bz) values('"+hm+"','"+pp+"','"+lx+"','"+cj+"','"+bz+"')");
					if(flag==Constant.SUCCESS){
						request.setAttribute("message", "操作成功！");
						request.getRequestDispatcher("admin/ts/index.jsp").forward(request, response);
					}
					else{
						request.setAttribute("message", "系统维护中！");
						request.getRequestDispatcher("admin/ts/index.jsp").forward(request, response);
					}
				 
			}
			else if(method.equals("upts")){ 
				String id=request.getParameter("id");
				String hm=request.getParameter("hm");
				String pp=request.getParameter("pp");
				String lx=request.getParameter("lx");
				String cj=request.getParameter("cj");
				String bz=request.getParameter("bz"); 
					int flag = cBean.comUp("update ts set hm='"+hm+"',pp='"+pp+"',lx='"+lx+"',cj='"+cj+"',bz='"+bz+"' where id='"+id+"'");
					if(flag == Constant.SUCCESS){
						request.setAttribute("message", "操作成功！");
						request.getRequestDispatcher("admin/ts/index.jsp").forward(request, response);
					}
					else{
						request.setAttribute("message", "操作失败！");
						request.getRequestDispatcher("admin/ts/index.jsp").forward(request, response);
					}
				 
			}
			//删除信息
			else if(method.equals("delts")){
				String id=request.getParameter("id"); 
				int flag=cBean.comUp("delete from ts where id='"+id+"'");
				if(flag==Constant.SUCCESS){
					 
					request.setAttribute("message", "操作成功！");
					request.getRequestDispatcher("admin/ts/index.jsp").forward(request, response);
				}
				else{
					request.setAttribute("message", "系统维护中！");
					request.getRequestDispatcher("admin/ts/index.jsp").forward(request, response);
				}
			} 
			
			
			
//			/		信息
//			信息
			else if(method.equals("addcc")){
				//String id="";String hm = "";String pp=""; String lx=""; String cj=""; String bz=""; 
				String hm=request.getParameter("hm");
				String pp=request.getParameter("pp");
				String lx=request.getParameter("lx");
				String cj=request.getParameter("cj");
				String bz=request.getParameter("bz");
				 
					int flag=cBean.comUp("insert into cc(hm,pp,lx,cj,bz) values('"+hm+"','"+pp+"','"+lx+"','"+cj+"','"+bz+"')");
					if(flag==Constant.SUCCESS){
						request.setAttribute("message", "操作成功！");
						request.getRequestDispatcher("admin/cc/index.jsp").forward(request, response);
					}
					else{
						request.setAttribute("message", "系统维护中！");
						request.getRequestDispatcher("admin/cc/index.jsp").forward(request, response);
					}
				 
			}
			else if(method.equals("upcc")){ 
				String id=request.getParameter("id");
				String hm=request.getParameter("hm");
				String pp=request.getParameter("pp");
				String lx=request.getParameter("lx");
				String cj=request.getParameter("cj");
				String bz=request.getParameter("bz"); 
					int flag = cBean.comUp("update cc set hm='"+hm+"',pp='"+pp+"',lx='"+lx+"',cj='"+cj+"',bz='"+bz+"' where id='"+id+"'");
					if(flag == Constant.SUCCESS){
						request.setAttribute("message", "操作成功！");
						request.getRequestDispatcher("admin/cc/index.jsp").forward(request, response);
					}
					else{
						request.setAttribute("message", "操作失败！");
						request.getRequestDispatcher("admin/cc/index.jsp").forward(request, response);
					}
				 
			}
			//删除信息
			else if(method.equals("delcc")){
				String id=request.getParameter("id"); 
				int flag=cBean.comUp("delete from cc where id='"+id+"'");
				if(flag==Constant.SUCCESS){
					 
					request.setAttribute("message", "操作成功！");
					request.getRequestDispatcher("admin/cc/index.jsp").forward(request, response);
				}
				else{
					request.setAttribute("message", "系统维护中！");
					request.getRequestDispatcher("admin/cc/index.jsp").forward(request, response);
				}
			} 
			
			
			
//			/		信息
//			信息
			else if(method.equals("addyh")){
				//String id="";String hm = "";String pp=""; String lx=""; String cj=""; String bz=""; 
				String hm=request.getParameter("hm");
				String pp=request.getParameter("pp");
				String lx=request.getParameter("lx");
				String cj=request.getParameter("cj");
				String bz=request.getParameter("bz");
				 
					int flag=cBean.comUp("insert into yh(hm,pp,lx,cj,bz) values('"+hm+"','"+pp+"','"+lx+"','"+cj+"','"+bz+"')");
					if(flag==Constant.SUCCESS){
						request.setAttribute("message", "操作成功！");
						request.getRequestDispatcher("admin/yh/index.jsp").forward(request, response);
					}
					else{
						request.setAttribute("message", "系统维护中！");
						request.getRequestDispatcher("admin/yh/index.jsp").forward(request, response);
					}
				 
			}
			else if(method.equals("upyh")){ 
				String id=request.getParameter("id");
				String hm=request.getParameter("hm");
				String pp=request.getParameter("pp");
				String lx=request.getParameter("lx");
				String cj=request.getParameter("cj");
				String bz=request.getParameter("bz"); 
					int flag = cBean.comUp("update yh set hm='"+hm+"',pp='"+pp+"',lx='"+lx+"',cj='"+cj+"',bz='"+bz+"' where id='"+id+"'");
					if(flag == Constant.SUCCESS){
						request.setAttribute("message", "操作成功！");
						request.getRequestDispatcher("admin/yh/index.jsp").forward(request, response);
					}
					else{
						request.setAttribute("message", "操作失败！");
						request.getRequestDispatcher("admin/yh/index.jsp").forward(request, response);
					}
				 
			}
			//删除信息
			else if(method.equals("delyh")){
				String id=request.getParameter("id"); 
				int flag=cBean.comUp("delete from yh where id='"+id+"'");
				if(flag==Constant.SUCCESS){
					 
					request.setAttribute("message", "操作成功！");
					request.getRequestDispatcher("admin/yh/index.jsp").forward(request, response);
				}
				else{
					request.setAttribute("message", "系统维护中！");
					request.getRequestDispatcher("admin/yh/index.jsp").forward(request, response);
				}
			} 
			
			
			
//			车信息
			else if(method.equals("addgycjk")){
				//String id="";String hm = "";String pp=""; String lx=""; String cj=""; String bz=""; 
				String hm=request.getParameter("hm");
				String pp=request.getParameter("pp");
				String lx=request.getParameter("lx");
				String cj=request.getParameter("cj");
				String bz=request.getParameter("bz");
				 
					int flag=cBean.comUp("insert into gycjk(hm,pp,lx,cj,bz) values('"+hm+"','"+pp+"','"+lx+"','"+cj+"','"+bz+"')");
					if(flag==Constant.SUCCESS){
						request.setAttribute("message", "操作成功！");
						request.getRequestDispatcher("admin/gycjk/index.jsp").forward(request, response);
					}
					else{
						request.setAttribute("message", "系统维护中！");
						request.getRequestDispatcher("admin/gycjk/index.jsp").forward(request, response);
					}
				 
			}
			else if(method.equals("upgycjk")){ 
				String id=request.getParameter("id");
				String hm=request.getParameter("hm");
				String pp=request.getParameter("pp");
				String lx=request.getParameter("lx");
				String cj=request.getParameter("cj");
				String bz=request.getParameter("bz"); 
					int flag = cBean.comUp("update gycjk set hm='"+hm+"',pp='"+pp+"',lx='"+lx+"',cj='"+cj+"',bz='"+bz+"' where id='"+id+"'");
					if(flag == Constant.SUCCESS){
						request.setAttribute("message", "操作成功！");
						request.getRequestDispatcher("admin/gycjk/index.jsp").forward(request, response);
					}
					else{
						request.setAttribute("message", "操作失败！");
						request.getRequestDispatcher("admin/gycjk/index.jsp").forward(request, response);
					}
				 
			}
			//删除信息
			else if(method.equals("delgycjk")){
				String id=request.getParameter("id"); 
				int flag=cBean.comUp("delete from gycjk where id='"+id+"'");
				if(flag==Constant.SUCCESS){
					 
					request.setAttribute("message", "操作成功！");
					request.getRequestDispatcher("admin/gycjk/index.jsp").forward(request, response);
				}
				else{
					request.setAttribute("message", "系统维护中！");
					request.getRequestDispatcher("admin/gycjk/index.jsp").forward(request, response);
				}
			} 
			
			
			
			
//			车信息
			else if(method.equals("addcbc")){
				//String id="";String hm = "";String pp=""; String lx=""; String cj=""; String bz=""; 
				String cid=request.getParameter("cid");
				String jsy=request.getParameter("jsy");
				String bz=request.getParameter("bz"); 
				String hm=cBean.getString("select hm from classes where id='"+cid+"'");
				String str=cBean.getString("select id from cbc where cid='"+cid+"'");
				if(str==null){
					int flag=cBean.comUp("insert into cbc(cid,jsy,bz,sj,hm) values('"+cid+"','"+jsy+"','"+bz+"','"+date2+"','"+hm+"')");
					if(flag==Constant.SUCCESS){
						request.setAttribute("message", "操作成功！");
						request.getRequestDispatcher("admin/cbc/index.jsp").forward(request, response);
					}
					else{
						request.setAttribute("message", "系统维护中！");
						request.getRequestDispatcher("admin/cbc/index.jsp").forward(request, response);
					}
				}
				else{
					request.setAttribute("message", "该车已！");
					request.getRequestDispatcher("admin/cbc/index.jsp").forward(request, response);
				} 
			}
			else if(method.equals("upcbc")){ 
				String id=request.getParameter("id");
				String cid=request.getParameter("cid");
				String jsy=request.getParameter("jsy");
				String bz=request.getParameter("bz"); 
				String hm=cBean.getString("select hm from classes where id='"+cid+"'");
				String str=cBean.getString("select jsy from cbc where cid='"+cid+"' and id!='"+id+"'");
				if(str==null){
					int flag = cBean.comUp("update cbc set cid='"+cid+"',jsy='"+jsy+"',bz='"+bz+"',hm='"+hm+"'  where id='"+id+"'");
					if(flag == Constant.SUCCESS){
						request.setAttribute("message", "操作成功！");
						request.getRequestDispatcher("admin/cbc/index.jsp").forward(request, response);
					}
					else{
						request.setAttribute("message", "操作失败！");
						request.getRequestDispatcher("admin/cbc/index.jsp").forward(request, response);
					}
				}
				else{
					request.setAttribute("message", "该车已！");
					request.getRequestDispatcher("admin/cbc/index.jsp").forward(request, response);
				}  
			}
			//删除车信息
			else if(method.equals("delcbc")){
				String id=request.getParameter("id"); 
				int flag=cBean.comUp("delete from cbc where id='"+id+"'");
				if(flag==Constant.SUCCESS){
					 
					request.setAttribute("message", "操作成功！");
					request.getRequestDispatcher("admin/cbc/index.jsp").forward(request, response);
				}
				else{
					request.setAttribute("message", "系统维护中！");
					request.getRequestDispatcher("admin/cbc/index.jsp").forward(request, response);
				}
			} 
			
			/////////////车
//			车信息
			else if(method.equals("addcbcjk")){
				//String id="";String hm = "";String pp=""; String lx=""; String cj=""; String bz=""; 
				String hm=request.getParameter("hm");
				String pp=request.getParameter("pp");
				String lx=request.getParameter("lx"); 
				String bz=request.getParameter("bz");
				 
					int flag=cBean.comUp("insert into cbcjk(hm,pp ,lx,bz) values('"+hm+"','"+pp+"','"+lx+"' ,'"+bz+"')");
					if(flag==Constant.SUCCESS){
						request.setAttribute("message", "操作成功！");
						request.getRequestDispatcher("admin/cbcjk/index.jsp").forward(request, response);
					}
					else{
						request.setAttribute("message", "系统维护中！");
						request.getRequestDispatcher("admin/cbcjk/index.jsp").forward(request, response);
					}
				 
			}
			else if(method.equals("upcbcjk")){ 
				String id=request.getParameter("id");
				String hm=request.getParameter("hm");
				String pp=request.getParameter("pp");  
				String lx=request.getParameter("lx"); 
				String bz=request.getParameter("bz"); 
					int flag = cBean.comUp("update cbcjk set hm='"+hm+"',pp='"+pp+"',lx='"+lx+"', bz='"+bz+"' where id='"+id+"'");
					if(flag == Constant.SUCCESS){
						request.setAttribute("message", "操作成功！");
						request.getRequestDispatcher("admin/cbcjk/index.jsp").forward(request, response);
					}
					else{
						request.setAttribute("message", "操作失败！");
						request.getRequestDispatcher("admin/cbcjk/index.jsp").forward(request, response);
					}
				 
			}
			//删除信息
			else if(method.equals("delcbcjk")){
				String id=request.getParameter("id"); 
				int flag=cBean.comUp("delete from cbcjk where id='"+id+"'");
				if(flag==Constant.SUCCESS){
					 
					request.setAttribute("message", "操作成功！");
					request.getRequestDispatcher("admin/cbcjk/index.jsp").forward(request, response);
				}
				else{
					request.setAttribute("message", "系统维护中！");
					request.getRequestDispatcher("admin/cbcjk/index.jsp").forward(request, response);
				}
			} 
			else if(method.equals("csh")){
				 
				cBean.comUp("delete from cbc ");
				cBean.comUp("delete from affiche ");
				cBean.comUp("delete from cc ");
				cBean.comUp("delete from classes ");
				cBean.comUp("delete from jsy ");
				cBean.comUp("delete from gycjk ");
				cBean.comUp("delete from jf ");
				cBean.comUp("delete from jsy ");
				cBean.comUp("delete from tb "); 
				cBean.comUp("delete from teacher ");
				cBean.comUp("delete from wz ");
				cBean.comUp("delete from zc "); 
					request.setAttribute("message", "操作成功！");
					request.getRequestDispatcher("admin/xt/index.jsp").forward(request, response);
				 
			} 
			
			
			
			else if(method.equals("bfdb")){
				try {       
		            Runtime rt = Runtime.getRuntime();       
		      
		            // 调用 mysql 的 cmd 
		Process child = rt.exec("D:/Program Files/MySQL/MySQL Server 5.5/bin/mysqldump -uroot -p123  czcgl");// 设置导出编码为utf8。这里必须是utf8       
		                  
		            // 把进程执行中的控制台输出信息写入.sql文件，即生成了备份文件。注：如果不对控制台信息进行读出，则会导致进程堵塞无法运行       
		            InputStream in = child.getInputStream();// 控制台的输出信息作为输入流       
		                              
		            InputStreamReader xx = new InputStreamReader(in, "utf8");// 设置输出流编码为utf8。这里必须是utf8，否则从流中读入的是乱 

		            String inStr;       
		            StringBuffer sb = new StringBuffer("");       
		            String outStr;       
		            // 组合控制台输出信息字符串       
		            BufferedReader br = new BufferedReader(xx);       
		            while ((inStr = br.readLine()) != null) {       
		                sb.append(inStr + "\r\n");       
		            }       
		            outStr = sb.toString();       
		                  
		            // 要用来做导入用的sql目标文件：       
		            FileOutputStream fout = new FileOutputStream(       
		                    "d:/db.sql");       
		            OutputStreamWriter writer = new OutputStreamWriter(fout, "utf8");       
		            writer.write(outStr);       
		            // 注：这里如果用缓冲方式写入文件的话，会导致中文乱码，用flush()方法则可以避免       
		            writer.flush();       
		      
		            // 别忘记关闭输入输出流       
		            in.close 
		();       
		             
		xx.close();       
		            br.close();       
		            writer.close();       
		            fout.close();       
		      
		            System.out.println("");       
		      
		        } catch (Exception e) {       
		            e.printStackTrace();       
		        }   
		        request.setAttribute("message", "操作成功！");
				request.getRequestDispatcher("admin/xt/bf.jsp").forward(request, response);
			} 
			else{//无参数传入转到错误页面
				request.getRequestDispatcher("error.jsp").forward(request, response);
			}
		}
		catch(Exception e){
			e.printStackTrace();
			return mapping.findForward("error.jsp"); 
		}
		return mapping.findForward(strr);
	} 
}