/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.device.struts.action;

import java.text.SimpleDateFormat;
import java.util.Calendar;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.bean.ComBean;
import com.util.Constant;

/** 
 * MyEclipse Struts
 * Creation date: 11-26-2013
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 */
public class LoginAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		try {
			request.setCharacterEncoding("gb2312");
		} catch (Exception ex) {
			// TODO Auto-generated catch block
			ex.printStackTrace();
		}	
		String strr="";
		try{
			ComBean cBean = new ComBean();
			String date=new SimpleDateFormat("yyyy-MM-dd HH:mm:ss").format(Calendar.getInstance().getTime());
			String date2=new SimpleDateFormat("yyyy-MM-dd").format(Calendar.getInstance().getTime());
			String method = request.getParameter("method");
			HttpSession session = request.getSession();
			if(method.equals("mlogin")){//用户登录
				String username = request.getParameter("username"); 
				String password = request.getParameter("password"); 
				String sf = request.getParameter("sf"); 
				if(sf.equals("管理员")){
					String str=cBean.getString("select id from admin where username='"+username+"' and  password='"+password+"'");
					if(str==null){
						request.setAttribute("message", "登录信息错误！");
						request.setAttribute("userType", "admin");
						request.getRequestDispatcher("login.jsp").forward(request, response); 
					}
					else{
						session.setAttribute("user", username);session.setAttribute("sf", sf);
						request.getRequestDispatcher("admin/index.jsp").forward(request, response); 
					}
				}
				else{
					String str=cBean.getString("select id from teacher where username='"+username+"' and  password='"+password+"'  and ifuse='在用'");
					if(str==null){
						request.setAttribute("message", "登录信息错误！");
						request.setAttribute("userType", "user");
						request.getRequestDispatcher("login.jsp").forward(request, response); 
					}
					else{
						session.setAttribute("user", username);session.setAttribute("sf", sf);
						request.getRequestDispatcher("admin/index.jsp").forward(request, response); 
					}
				}
				
			}
			// 跳到注册页面
			else if(method.equals("reg")){
				session.removeAttribute("member");
				request.getRequestDispatcher("reg.jsp").forward(request, response);
			}
			// 注册
			else if(method.equals("doReg")){
				String username = request.getParameter("username"); 
				String password = request.getParameter("password");
				String sex = request.getParameter("sex");
				String age = request.getParameter("age");
				String tel = request.getParameter("tel");
				String address = request.getParameter("address");
				String sf = request.getParameter("sf"); 
				if(sf.equals("用户")) {
					int flag=cBean.comUp("insert into teacher(username,password,sex,age,tel,address,ifuse) values('"+username+"','"+password+"','"+sex+"','"+age+"','"+tel+"','"+address+"','"+"在用"+"')");
					if(flag==Constant.SUCCESS){
						request.setAttribute("message", "操作成功！");
						request.getRequestDispatcher("admin/index.jsp").forward(request, response);
					}
					else{
						request.setAttribute("message", "系统维护中！");
						request.getRequestDispatcher("admin/index.jsp").forward(request, response);
					}
				} else {
					int flag=cBean.comUp("insert into admin(username,password,sex,age,address,tel,addtime) values('"+username+"','"+password+"','"+sex+"','"+age+"','"+address+"','"+tel+"','"+date+"')");
					if(flag==Constant.SUCCESS){
						request.setAttribute("message", "操作成功！");
						request.getRequestDispatcher("admin/index.jsp").forward(request, response);
					}
					else{
						request.setAttribute("message", "系统维护中！");
						request.getRequestDispatcher("admin/index.jsp").forward(request, response);
					}
				}
			}
			else if(method.equals("memberexit")){ //退出登录
				session.removeAttribute("member");
				request.getRequestDispatcher("index.jsp").forward(request, response);
			}
			else if(method.equals("muppwd")){// 修改密码
				String member=(String)session.getAttribute("member"); 
				String oldpwd = request.getParameter("oldpwd"); 
				String newpwd = request.getParameter("newpwd"); 
				String str=cBean.getString("select id from teacher where username='"+member+"' and  password='"+oldpwd+"'");
				if(str==null){
					request.setAttribute("message", "原始密码信息错误！");
					request.getRequestDispatcher("teacher/info/editpwd.jsp").forward(request, response); 
				}
				else{
					int flag=cBean.comUp("update teacher set password='"+newpwd+"' where username='"+member+"'");
					if(flag == Constant.SUCCESS){ 
						request.setAttribute("message", "操作成功！");
						request.getRequestDispatcher("teacher/info/editpwd.jsp").forward(request, response); 
					}
					else { 
						request.setAttribute("message", "操作失败！");
						request.getRequestDispatcher("teacher/info/editpwd.jsp").forward(request, response); 
					}
				}
			} 
			 
			else{//无参数传入转到错误页面
				request.getRequestDispatcher("error.jsp").forward(request, response);
			}
		}
		catch(Exception e){
			e.printStackTrace();
			return mapping.findForward("error.jsp"); 
		}
		return mapping.findForward(strr);
	} 
}