package com.hibernate;

/**
 * AssForumLeave generated by MyEclipse Persistence Tools
 */

public class AssForumLeave implements java.io.Serializable {

	// Fields

	private Integer id;

	private Integer UId;

	private Integer AFId;

	private String count;

	private String date;

	// Constructors

	/** default constructor */
	public AssForumLeave() {
	}

	/** minimal constructor */
	public AssForumLeave(Integer id) {
		this.id = id;
	}

	/** full constructor */
	public AssForumLeave(Integer id, Integer UId, Integer AFId, String count,
			String date) {
		this.id = id;
		this.UId = UId;
		this.AFId = AFId;
		this.count = count;
		this.date = date;
	}

	// Property accessors

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getUId() {
		return this.UId;
	}

	public void setUId(Integer UId) {
		this.UId = UId;
	}

	public Integer getAFId() {
		return this.AFId;
	}

	public void setAFId(Integer AFId) {
		this.AFId = AFId;
	}

	public String getCount() {
		return this.count;
	}

	public void setCount(String count) {
		this.count = count;
	}

	public String getDate() {
		return this.date;
	}

	public void setDate(String date) {
		this.date = date;
	}

}