package com.hibernate;

/**
 * Assn generated by MyEclipse Persistence Tools
 */

public class Assn implements java.io.Serializable {

	// Fields

	private Integer id;

	private String name;

	private Integer UId;

	private String count;

	// Constructors

	/** default constructor */
	public Assn() {
	}

	/** minimal constructor */
	public Assn(Integer id) {
		this.id = id;
	}

	/** full constructor */
	public Assn(Integer id, String name, Integer UId, String count) {
		this.id = id;
		this.name = name;
		this.UId = UId;
		this.count = count;
	}

	// Property accessors

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Integer getUId() {
		return this.UId;
	}

	public void setUId(Integer UId) {
		this.UId = UId;
	}

	public String getCount() {
		return this.count;
	}

	public void setCount(String count) {
		this.count = count;
	}

}