package com.hibernate;

/**
 * AssnForum generated by MyEclipse Persistence Tools
 */

public class AssnForum implements java.io.Serializable {

	// Fields

	private Integer id;

	private String title;

	private String count;

	private String date;

	private Integer UId;

	// Constructors

	/** default constructor */
	public AssnForum() {
	}

	/** minimal constructor */
	public AssnForum(Integer id) {
		this.id = id;
	}

	/** full constructor */
	public AssnForum(Integer id, String title, String count, String date,
			Integer UId) {
		this.id = id;
		this.title = title;
		this.count = count;
		this.date = date;
		this.UId = UId;
	}

	// Property accessors

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getCount() {
		return this.count;
	}

	public void setCount(String count) {
		this.count = count;
	}

	public String getDate() {
		return this.date;
	}

	public void setDate(String date) {
		this.date = date;
	}

	public Integer getUId() {
		return this.UId;
	}

	public void setUId(Integer UId) {
		this.UId = UId;
	}

}