package com.hibernate;

/**
 * Classes generated by MyEclipse Persistence Tools
 */

public class Classes implements java.io.Serializable {

	// Fields

	private Integer id;

	private Integer schoolId;

	private String departId;

	private String classname;

	private Integer UId;

	private String affiche;

	// Constructors

	/** default constructor */
	public Classes() {
	}

	/** minimal constructor */
	public Classes(Integer id) {
		this.id = id;
	}

	/** full constructor */
	public Classes(Integer id, Integer schoolId, String departId,
			String classname, Integer UId, String affiche) {
		this.id = id;
		this.schoolId = schoolId;
		this.departId = departId;
		this.classname = classname;
		this.UId = UId;
		this.affiche = affiche;
	}

	// Property accessors

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getSchoolId() {
		return this.schoolId;
	}

	public void setSchoolId(Integer schoolId) {
		this.schoolId = schoolId;
	}

	public String getDepartId() {
		return this.departId;
	}

	public void setDepartId(String departId) {
		this.departId = departId;
	}

	public String getClassname() {
		return this.classname;
	}

	public void setClassname(String classname) {
		this.classname = classname;
	}

	public Integer getUId() {
		return this.UId;
	}

	public void setUId(Integer UId) {
		this.UId = UId;
	}

	public String getAffiche() {
		return this.affiche;
	}

	public void setAffiche(String affiche) {
		this.affiche = affiche;
	}

}