package com.hibernate;

/**
 * ClassLeave generated by MyEclipse Persistence Tools
 */

public class ClassLeave implements java.io.Serializable {

	// Fields

	private Integer id;

	private String count;

	private Integer UId;
	
	private Integer ClassId;

	private String date;
	
	private String name;
	
	private String url;

	// Constructors

	public String getUrl() {
		return url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	/** default constructor */
	public ClassLeave() {
	}

	/** minimal constructor */
	public ClassLeave(Integer id) {
		this.id = id;
	}

	/** full constructor */
	public ClassLeave(Integer id, String count, Integer ClassId,Integer UId, String date,
			String name,String url) {
		this.name = name;
		this.url = url;
		this.id = id;
		this.count = count;
		this.UId = UId;
		this.date = date;
		this.ClassId = ClassId;
	}

	// Property accessors

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getCount() {
		return this.count;
	}

	public void setCount(String count) {
		this.count = count;
	}

	public Integer getUId() {
		return this.UId;
	}

	public void setUId(Integer UId) {
		this.UId = UId;
	}

	public String getDate() {
		return this.date;
	}

	public void setDate(String date) {
		this.date = date;
	}

	public Integer getClassId() {
		return ClassId;
	}

	public void setClassId(Integer classId) {
		ClassId = classId;
	}

}