package com.hibernate;

/**
 * ClassPhoto generated by MyEclipse Persistence Tools
 */

public class ClassPhoto implements java.io.Serializable {

	// Fields

	private Integer id;

	private Integer classId;

	private String photo;

	private String date;

	// Constructors

	/** default constructor */
	public ClassPhoto() {
	}

	/** minimal constructor */
	public ClassPhoto(Integer id) {
		this.id = id;
	}

	/** full constructor */
	public ClassPhoto(Integer id, Integer classId, String photo, String date) {
		this.id = id;
		this.classId = classId;
		this.photo = photo;
		this.date = date;
	}

	// Property accessors

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getClassId() {
		return this.classId;
	}

	public void setClassId(Integer classId) {
		this.classId = classId;
	}

	public String getPhoto() {
		return this.photo;
	}

	public void setPhoto(String photo) {
		this.photo = photo;
	}

	public String getDate() {
		return this.date;
	}

	public void setDate(String date) {
		this.date = date;
	}

}