package com.hibernate;

/**
 * Firend generated by MyEclipse Persistence Tools
 */

public class Firend implements java.io.Serializable {

	// Fields

	private Integer id;

	private Integer UId;

	private Integer FId;

	private String name;

	private String url;

	// Constructors

	/** default constructor */
	public Firend() {
	}

	/** minimal constructor */
	public Firend(Integer id) {
		this.id = id;
	}

	/** full constructor */
	public Firend(Integer id, Integer UId, Integer FId, String name, String url) {
		this.id = id;
		this.UId = UId;
		this.FId = FId;
		this.name = name;
		this.url = url;
	}

	// Property accessors

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getUId() {
		return this.UId;
	}

	public void setUId(Integer UId) {
		this.UId = UId;
	}

	public Integer getFId() {
		return this.FId;
	}

	public void setFId(Integer FId) {
		this.FId = FId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

}