package com.hibernate;

/**
 * GeLeave generated by MyEclipse Persistence Tools
 */

public class GeLeave implements java.io.Serializable {

	// Fields

	private Integer id;

	private Integer UId;

	private String leId;

	private String url;

	private String count;

	private String date;
	
	private String name;

	// Constructors

	/** default constructor */
	public GeLeave() {
	}

	/** minimal constructor */
	public GeLeave(Integer id) {
		this.id = id;
	}

	/** full constructor */
	public GeLeave(Integer id, Integer UId, String leId, String url,
			String count, String date,String name) {
		this.id = id;
		this.UId = UId;
		this.leId = leId;
		this.url = url;
		this.count = count;
		this.date = date;
		this.name = name;
	}

	// Property accessors

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getUId() {
		return this.UId;
	}

	public void setUId(Integer UId) {
		this.UId = UId;
	}

	public String getLeId() {
		return this.leId;
	}

	public void setLeId(String leId) {
		this.leId = leId;
	}

	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	public String getCount() {
		return this.count;
	}

	public void setCount(String count) {
		this.count = count;
	}

	public String getDate() {
		return this.date;
	}

	public void setDate(String date) {
		this.date = date;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

}