package com.hibernate;

/**
 * GPhoto generated by MyEclipse Persistence Tools
 */

public class GPhoto implements java.io.Serializable {

	// Fields

	private Integer id;

	private Integer UId;

	private String photo;

	private String date;

	// Constructors

	/** default constructor */
	public GPhoto() {
	}

	/** minimal constructor */
	public GPhoto(Integer id) {
		this.id = id;
	}

	/** full constructor */
	public GPhoto(Integer id, Integer UId, String photo, String date) {
		this.id = id;
		this.UId = UId;
		this.photo = photo;
		this.date = date;
	}

	// Property accessors

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getUId() {
		return this.UId;
	}

	public void setUId(Integer UId) {
		this.UId = UId;
	}

	public String getPhoto() {
		return this.photo;
	}

	public void setPhoto(String photo) {
		this.photo = photo;
	}

	public String getDate() {
		return this.date;
	}

	public void setDate(String date) {
		this.date = date;
	}

}