package com.hibernate;

/**
 * Intro generated by MyEclipse Persistence Tools
 */

public class Intro implements java.io.Serializable {

	// Fields

	private Integer id;

	private String name;

	private String classes;

	private String department;

	private String school;

	private String sex;

	private String address;

	private String tel;

	private String qq;

	private String msn;

	private String year;

	private String time;

	private String url;

	private String per;

	// Constructors

	/** default constructor */
	public Intro() {
	}

	/** minimal constructor */
	public Intro(Integer id) {
		this.id = id;
	}

	/** full constructor */
	public Intro(Integer id, String name, String classes, String department,
			String school, String sex, String address, String tel, String qq,
			String msn, String year, String time, String url, String per) {
		this.id = id;
		this.name = name;
		this.classes = classes;
		this.department = department;
		this.school = school;
		this.sex = sex;
		this.address = address;
		this.tel = tel;
		this.qq = qq;
		this.msn = msn;
		this.year = year;
		this.time = time;
		this.url = url;
		this.per = per;
	}

	// Property accessors

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getClasses() {
		return this.classes;
	}

	public void setClasses(String classes) {
		this.classes = classes;
	}

	public String getDepartment() {
		return this.department;
	}

	public void setDepartment(String department) {
		this.department = department;
	}

	public String getSchool() {
		return this.school;
	}

	public void setSchool(String school) {
		this.school = school;
	}

	public String getSex() {
		return this.sex;
	}

	public void setSex(String sex) {
		this.sex = sex;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getTel() {
		return this.tel;
	}

	public void setTel(String tel) {
		this.tel = tel;
	}

	public String getQq() {
		return this.qq;
	}

	public void setQq(String qq) {
		this.qq = qq;
	}

	public String getMsn() {
		return this.msn;
	}

	public void setMsn(String msn) {
		this.msn = msn;
	}

	public String getYear() {
		return this.year;
	}

	public void setYear(String year) {
		this.year = year;
	}

	public String getTime() {
		return this.time;
	}

	public void setTime(String time) {
		this.time = time;
	}

	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	public String getPer() {
		return this.per;
	}

	public void setPer(String per) {
		this.per = per;
	}

}