package com.hibernate;

/**
 * Mails generated by MyEclipse Persistence Tools
 */

public class Mails implements java.io.Serializable {

	// Fields

	private Integer id;

	private Integer UId;

	private String name;

	private String title;

	private String count;

	private String date;
	
	private String type;

	// Constructors

	public String getType() {
		return type;
	}

	public void setType(String type) {
		this.type = type;
	}

	/** default constructor */
	public Mails() {
	}

	/** minimal constructor */
	public Mails(Integer id) {
		this.id = id;
	}

	/** full constructor */
	public Mails(Integer id, Integer UId, String name, String title,
			String count, String date,String type) {
		this.id = id;
		this.UId = UId;
		this.name = name;
		this.title = title;
		this.count = count;
		this.date = date;
		this.type = type;
	}

	// Property accessors

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getUId() {
		return this.UId;
	}

	public void setUId(Integer UId) {
		this.UId = UId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getCount() {
		return this.count;
	}

	public void setCount(String count) {
		this.count = count;
	}

	public String getDate() {
		return this.date;
	}

	public void setDate(String date) {
		this.date = date;
	}

}