package com.hibernate;

/**
 * SchoolLeave generated by MyEclipse Persistence Tools
 */

public class SchoolLeave implements java.io.Serializable {

	// Fields

	private Integer id;

	private Integer forumId;

	private String count;

	private String date;

	private Integer UId;

	// Constructors

	/** default constructor */
	public SchoolLeave() {
	}

	/** minimal constructor */
	public SchoolLeave(Integer id) {
		this.id = id;
	}

	/** full constructor */
	public SchoolLeave(Integer id, Integer forumId, String count, String date,
			Integer UId) {
		this.id = id;
		this.forumId = forumId;
		this.count = count;
		this.date = date;
		this.UId = UId;
	}

	// Property accessors

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getForumId() {
		return this.forumId;
	}

	public void setForumId(Integer forumId) {
		this.forumId = forumId;
	}

	public String getCount() {
		return this.count;
	}

	public void setCount(String count) {
		this.count = count;
	}

	public String getDate() {
		return this.date;
	}

	public void setDate(String date) {
		this.date = date;
	}

	public Integer getUId() {
		return this.UId;
	}

	public void setUId(Integer UId) {
		this.UId = UId;
	}

}