package com.hibernate;

/**
 * SchoolForum generated by MyEclipse Persistence Tools
 */

public class SchoolForum implements java.io.Serializable {

	// Fields

	private Integer id;

	private Integer schoolId;

	private String name;

	private String title;

	private String count;

	private String date;

	// Constructors

	/** default constructor */
	public SchoolForum() {
	}

	/** minimal constructor */
	public SchoolForum(Integer id) {
		this.id = id;
	}

	/** full constructor */
	public SchoolForum(Integer id, Integer schoolId, String name, String title,
			String count, String date) {
		this.id = id;
		this.schoolId = schoolId;
		this.name = name;
		this.title = title;
		this.count = count;
		this.date = date;
	}

	// Property accessors

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getSchoolId() {
		return this.schoolId;
	}

	public void setSchoolId(Integer schoolId) {
		this.schoolId = schoolId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getCount() {
		return this.count;
	}

	public void setCount(String count) {
		this.count = count;
	}

	public String getDate() {
		return this.date;
	}

	public void setDate(String date) {
		this.date = date;
	}

}