package com.hibernate;

/**
 * Techer generated by MyEclipse Persistence Tools
 */

public class Techer implements java.io.Serializable {

	// Fields

	private Integer id;

	private Integer schoolId;

	private String name;

	private String tel;

	private String model;

	private String address;
	
	private String url;

	// Constructors

	public String getUrl() {
		return url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	/** default constructor */
	public Techer() {
	}

	/** minimal constructor */
	public Techer(Integer id) {
		this.id = id;
	}

	/** full constructor */
	public Techer(Integer id, Integer schoolId, String name, String tel,
			String model, String address,String url) {
		this.id = id;
		this.schoolId = schoolId;
		this.name = name;
		this.tel = tel;
		this.model = model;
		this.address = address;
		this.url = url;
	}

	// Property accessors

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getSchoolId() {
		return this.schoolId;
	}

	public void setSchoolId(Integer schoolId) {
		this.schoolId = schoolId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getTel() {
		return this.tel;
	}

	public void setTel(String tel) {
		this.tel = tel;
	}

	public String getModel() {
		return this.model;
	}

	public void setModel(String model) {
		this.model = model;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

}