package com.hibernate;

/**
 * UAssn generated by MyEclipse Persistence Tools
 */

public class UAssn implements java.io.Serializable {

	// Fields

	private Integer id;

	private Integer UId;

	private Integer assnId;

	// Constructors

	/** default constructor */
	public UAssn() {
	}

	/** minimal constructor */
	public UAssn(Integer id) {
		this.id = id;
	}

	/** full constructor */
	public UAssn(Integer id, Integer UId, Integer assnId) {
		this.id = id;
		this.UId = UId;
		this.assnId = assnId;
	}

	// Property accessors

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getUId() {
		return this.UId;
	}

	public void setUId(Integer UId) {
		this.UId = UId;
	}

	public Integer getAssnId() {
		return this.assnId;
	}

	public void setAssnId(Integer assnId) {
		this.assnId = assnId;
	}

}