package com.hibernate;

/**
 * Users generated by MyEclipse Persistence Tools
 */

public class Users implements java.io.Serializable {

	// Fields

	private Integer id;

	private Integer inroId;

	private String username;

	private String password;

	private String pruview;

	private String auditing;

	// Constructors

	/** default constructor */
	public Users() {
	}

	/** minimal constructor */
	public Users(Integer id) {
		this.id = id;
	}

	/** full constructor */
	public Users(Integer id, Integer inroId, String username, String password,
			String pruview, String auditing) {
		this.id = id;
		this.inroId = inroId;
		this.username = username;
		this.password = password;
		this.pruview = pruview;
		this.auditing = auditing;
	}

	// Property accessors

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getInroId() {
		return this.inroId;
	}

	public void setInroId(Integer inroId) {
		this.inroId = inroId;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getPruview() {
		return this.pruview;
	}

	public void setPruview(String pruview) {
		this.pruview = pruview;
	}

	public String getAuditing() {
		return this.auditing;
	}

	public void setAuditing(String auditing) {
		this.auditing = auditing;
	}

}