<%@ page language="java" import="java.util.*" pageEncoding="utf-8"%><% String path = request.getContextPath(); String basePath = request.getScheme() + "://" + request.getServerName() + ":" + request.getServerPort() + path + "/";%><!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"><html><head><title></title><link rel="stylesheet" type="text/css" href="css/csstree.css"></head><SCRIPT LANGUAGE="JavaScript" SRC="js/treemenu.js"></SCRIPT><SCRIPT LANGUAGE="JavaScript" SRC="js/Common.js"></SCRIPT><link href="css/csstree.css" rel="stylesheet" rev="stylesheet" type="text/css" media="all"><body><table><tr><td><script language='JavaScript'>foldersTree = gFldr('<DIV CLASS=fldrroot><b>系统功能列表</b></DIV>','');
Class1 = insFldr(foldersTree, gFldr('<DIV CLASS=fldrroot>users管理</DIV>', ''));insDoc(Class1, gLnk(1, '<a href=create系统用户Action target=main alt=新增users>新增users</a>', '', 'images/editinfo.gif'));
insDoc(Class1, gLnk(1, '<a href=list系统用户Action target=main alt=users列表>users列表</a>', '', 'images/editinfo.gif'));
insDoc(Class1, gLnk(1, '<a href=query系统用户.jsp target=main alt=users查询>users查询</a>', '', 'images/editinfo.gif'));
Class2 = insFldr(foldersTree, gFldr('<DIV CLASS=fldrroot>article管理</DIV>', ''));insDoc(Class2, gLnk(2, '<a href=create活动公告Action target=main alt=新增article>新增article</a>', '', 'images/editinfo.gif'));
insDoc(Class2, gLnk(2, '<a href=list活动公告Action target=main alt=article列表>article列表</a>', '', 'images/editinfo.gif'));
insDoc(Class2, gLnk(2, '<a href=query活动公告.jsp target=main alt=article查询>article查询</a>', '', 'images/editinfo.gif'));
Class3 = insFldr(foldersTree, gFldr('<DIV CLASS=fldrroot>contactus管理</DIV>', ''));insDoc(Class3, gLnk(3, '<a href=create联系我们Action target=main alt=新增contactus>新增contactus</a>', '', 'images/editinfo.gif'));
insDoc(Class3, gLnk(3, '<a href=list联系我们Action target=main alt=contactus列表>contactus列表</a>', '', 'images/editinfo.gif'));
insDoc(Class3, gLnk(3, '<a href=query联系我们.jsp target=main alt=contactus查询>contactus查询</a>', '', 'images/editinfo.gif'));
Class4 = insFldr(foldersTree, gFldr('<DIV CLASS=fldrroot>aboutus管理</DIV>', ''));insDoc(Class4, gLnk(4, '<a href=create公司简介Action target=main alt=新增aboutus>新增aboutus</a>', '', 'images/editinfo.gif'));
insDoc(Class4, gLnk(4, '<a href=list公司简介Action target=main alt=aboutus列表>aboutus列表</a>', '', 'images/editinfo.gif'));
insDoc(Class4, gLnk(4, '<a href=query公司简介.jsp target=main alt=aboutus查询>aboutus查询</a>', '', 'images/editinfo.gif'));
Class5 = insFldr(foldersTree, gFldr('<DIV CLASS=fldrroot>atts管理</DIV>', ''));insDoc(Class5, gLnk(5, '<a href=create景点Action target=main alt=新增atts>新增atts</a>', '', 'images/editinfo.gif'));
insDoc(Class5, gLnk(5, '<a href=list景点Action target=main alt=atts列表>atts列表</a>', '', 'images/editinfo.gif'));
insDoc(Class5, gLnk(5, '<a href=query景点.jsp target=main alt=atts查询>atts查询</a>', '', 'images/editinfo.gif'));
Class6 = insFldr(foldersTree, gFldr('<DIV CLASS=fldrroot>cate管理</DIV>', ''));insDoc(Class6, gLnk(6, '<a href=create线路类型Action target=main alt=新增cate>新增cate</a>', '', 'images/editinfo.gif'));
insDoc(Class6, gLnk(6, '<a href=list线路类型Action target=main alt=cate列表>cate列表</a>', '', 'images/editinfo.gif'));
insDoc(Class6, gLnk(6, '<a href=query线路类型.jsp target=main alt=cate查询>cate查询</a>', '', 'images/editinfo.gif'));
Class7 = insFldr(foldersTree, gFldr('<DIV CLASS=fldrroot>lines管理</DIV>', ''));insDoc(Class7, gLnk(7, '<a href=create旅游线路Action target=main alt=新增lines>新增lines</a>', '', 'images/editinfo.gif'));
insDoc(Class7, gLnk(7, '<a href=list旅游线路Action target=main alt=lines列表>lines列表</a>', '', 'images/editinfo.gif'));
insDoc(Class7, gLnk(7, '<a href=query旅游线路.jsp target=main alt=lines查询>lines查询</a>', '', 'images/editinfo.gif'));
Class8 = insFldr(foldersTree, gFldr('<DIV CLASS=fldrroot>lines管理</DIV>', ''));insDoc(Class8, gLnk(8, '<a href=create旅游线路Action target=main alt=新增lines>新增lines</a>', '', 'images/editinfo.gif'));
insDoc(Class8, gLnk(8, '<a href=list旅游线路Action target=main alt=lines列表>lines列表</a>', '', 'images/editinfo.gif'));
insDoc(Class8, gLnk(8, '<a href=query旅游线路.jsp target=main alt=lines查询>lines查询</a>', '', 'images/editinfo.gif'));
Class9 = insFldr(foldersTree, gFldr('<DIV CLASS=fldrroot>cart管理</DIV>', ''));insDoc(Class9, gLnk(9, '<a href=create购物车Action target=main alt=新增cart>新增cart</a>', '', 'images/editinfo.gif'));
insDoc(Class9, gLnk(9, '<a href=list购物车Action target=main alt=cart列表>cart列表</a>', '', 'images/editinfo.gif'));
insDoc(Class9, gLnk(9, '<a href=query购物车.jsp target=main alt=cart查询>cart查询</a>', '', 'images/editinfo.gif'));
Class10 = insFldr(foldersTree, gFldr('<DIV CLASS=fldrroot>orders管理</DIV>', ''));insDoc(Class10, gLnk(10, '<a href=create订单Action target=main alt=新增orders>新增orders</a>', '', 'images/editinfo.gif'));
insDoc(Class10, gLnk(10, '<a href=list订单Action target=main alt=orders列表>orders列表</a>', '', 'images/editinfo.gif'));
insDoc(Class10, gLnk(10, '<a href=query订单.jsp target=main alt=orders查询>orders查询</a>', '', 'images/editinfo.gif'));
Class11 = insFldr(foldersTree, gFldr('<DIV CLASS=fldrroot>orderdetail管理</DIV>', ''));insDoc(Class11, gLnk(11, '<a href=create订单明细Action target=main alt=新增orderdetail>新增orderdetail</a>', '', 'images/editinfo.gif'));
insDoc(Class11, gLnk(11, '<a href=list订单明细Action target=main alt=orderdetail列表>orderdetail列表</a>', '', 'images/editinfo.gif'));
insDoc(Class11, gLnk(11, '<a href=query订单明细.jsp target=main alt=orderdetail查询>orderdetail查询</a>', '', 'images/editinfo.gif'));
Class12 = insFldr(foldersTree, gFldr('<DIV CLASS=fldrroot>topic管理</DIV>', ''));insDoc(Class12, gLnk(12, '<a href=create用户留言Action target=main alt=新增topic>新增topic</a>', '', 'images/editinfo.gif'));
insDoc(Class12, gLnk(12, '<a href=list用户留言Action target=main alt=topic列表>topic列表</a>', '', 'images/editinfo.gif'));
insDoc(Class12, gLnk(12, '<a href=query用户留言.jsp target=main alt=topic查询>topic查询</a>', '', 'images/editinfo.gif'));
Class13 = insFldr(foldersTree, gFldr('<DIV CLASS=fldrroot>retopic管理</DIV>', ''));insDoc(Class13, gLnk(13, '<a href=create留言回复Action target=main alt=新增retopic>新增retopic</a>', '', 'images/editinfo.gif'));
insDoc(Class13, gLnk(13, '<a href=list留言回复Action target=main alt=retopic列表>retopic列表</a>', '', 'images/editinfo.gif'));
insDoc(Class13, gLnk(13, '<a href=query留言回复.jsp target=main alt=retopic查询>retopic查询</a>', '', 'images/editinfo.gif'));
insDoc(foldersTree, gLnk(1,'退出系统','<%=basePath %>','images/exit.gif'));
initializeDocument(0);
</script>
</td></tr>